### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by JakubMazur** [codemeister64/SwiftyPoeditor#1]
Hi, thanks for this. Very useful for my project. Any chance to add this to Homebrew so as a part of automatic build process there is no need to refetch and reinstall repository on VM?

**Comment by codemeister64** [comment]
Hi, thanks for the suggestion. 
I will try to look into it in the coming days.

**Comment by codemeister64** [comment]
Hi @JakubMazur,
I've added homebrew support and updated README instructions.

You can install it via:

```bash
brew tap codemeister64/swiftypoeditor
brew install swiftypoeditor
```

or

```bash
brew install codemeister64/swiftypoeditor/swiftypoeditor
```

**Comment by JakubMazur** [comment]
Awesome, thank you!
