### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by danipralea** [codemeister64/SwiftyPoeditor#6]
Hello I tried implementing the demo, but it does not work. I get the following error:
![image](https://user-images.githubusercontent.com/768893/113562029-1b7fc900-960e-11eb-8d6d-ee7e10af8b62.png)

EDIT:
seems like this did it:
```swift
extension String {
    var localized: String {
        return NSLocalizedString(self, tableName: nil, bundle: Bundle.main, value: "", comment: "")
    }
}
```

**Comment by danipralea** [comment]
Hello I tried implementing the demo, but it does not work
![Uploading image.png…]()

**Comment by codemeister64** [comment]
Hi! 
Yeah, you are right! 
Yes, .localized is another string extension.
Thank you, I will update the description
